Update testing_commit_msg.yml rev1

diff --git a/.github/workflows/testing_commit_msg.yml b/.github/workflows/testing_commit_msg.yml
--- a/.github/workflows/testing_commit_msg.yml
+++ b/.github/workflows/testing_commit_msg.yml
@@ -20,20 +20,23 @@ jobs:
         env:
           AZURE_DEVOPS_ORG: "Kyndryl"
           AZURE_DEVOPS_PROJECT: "ResiliencyEng"
-          AZURE_DEVOPS_PAT: "ggoubhcd57adyrhrcje5jy4ztmxq25xy2fywom7tk3my4qwqr4pa" # Create a GitHub secret for your Azure DevOps Personal Access Token
+          AZURE_DEVOPS_PAT: "${{ secrets.AZURE_DEVOPS_PAT }}" # Create a GitHub secret for your Azure DevOps Personal Access Token
         run: |
           commit_message=$(git log -1 --no-merges --pretty=%B)
-          echo Latest message is : $commit_message
-          if ! echo "$commit_message" | grep -E -q '\bAB#[0-9]+\b'; then
-            echo "Commit message should contain AB# followed by a number and separated from other text by a space"
-            exit 1
-          fi
+          echo "Latest message is: $commit_message"
 
-          id=$(git log --pretty=%B | head -n 1 | grep -Eo 'AB#[0-9]+' | cut -d '#' -f 2)
+          # Try to extract Ticket ID from commit message
+          id=$(echo "$commit_message" |grep -E -q '\bAB#[0-9]+\b' | cut -d '#' -f 2)
+
           if [[ -z "$id" ]]; then
-            echo "Unable to find Ticket ID in commit message. Proceeding with PR title"
-            pr_title_id=$(echo "${{ github.event.pull_request.title }}" | grep -Eo 'AB#[0-9]+' | cut -d '#' -f 2)
-            id=$pr_title_id
+            # If Ticket ID not found in commit message, extract from PR title
+            pr_title_id=$(echo "${{ github.event.pull_request.title }}" | grep -E -q '\bAB#[0-9]+\b' | cut -d '#' -f 2)
+            if [[ -z "$pr_title_id" ]]; then
+              echo "Unable to find Ticket ID in commit message or PR title. Aborting."
+              exit 1
+            else
+              id=$pr_title_id
+            fi
           fi
 
           # Validate Azure DevOps work item IDs
